namespace Cobilas.IO.Atlf.Components;
/// <summary>Represents the types of lexical tokens in the ATLF format.</summary>
/// <remarks>
/// This enumeration defines all possible token types that can be generated by the ATLF lexer.
/// Each token type corresponds to specific syntactic elements in the ATLF language.
/// </remarks>
public enum TokenType : byte {
	/// <summary>Represents an undefined or empty token.</summary>
	None = 0,
	/// <summary>Corresponds to the <c>"#&gt;"</c> token that opens a comment block.</summary>
	CommentOpen = 1,
	/// <summary>Corresponds to the <c>"&lt;#"</c> token that closes a comment block.</summary>
	CommentClose = 2,
	/// <summary>Corresponds to the <c>"#!"</c> token that opens a tag and its identifier.</summary>
	MarkOpen = 3,
	/// <summary>Corresponds to the <c>":"</c> token that closes a tag and its identifier.</summary>
	Colon = 4,
	/// <summary>Corresponds to the <c>"/*"</c> token that opens a tag's text block.</summary>
	BlockOpen = 5,
	/// <summary>Corresponds to the <c>"*/"</c> token that closes a tag's text block.</summary>
	BlockClose = 6,
	/// <summary>Represents the name of a tag.</summary>
	Identifier = 7,
	/// <summary>Represents the textual content within a tag.</summary>
	Text = 8,
	/// <summary>Indicates the end of the input stream.</summary>
	EndOfFile = 9
}